spring.application.name=v-app

spring.cloud.consul.enabled=false
spring.cloud.discovery.enabled=false
#prod if need consul
#spring.cloud.consul.host=10.0.1.250
#spring.cloud.consul.port=8500
#spring.cloud.consul.discovery.enabled=true

server.port=2000
server.servlet.context-path=/v-app